### ISSUE TITLE
data validation problem in Police CRUD

### ISSUE THREAD

**Issue by AnisH1427** [AnisH1427/Traffic-Management-System#10]
Hello Contributor,
<img width="796" alt="image" src="https://user-images.githubusercontent.com/102788439/229297158-c765c681-580f-4362-ae65-1efebfac83ce.png">
In Traffic Police section, unwanted data are also getting entered in database. For instance, mobile no not equals to length10, invalid email entry, are allowed to add as Traffic_police details. So, please take care of it, Thank you.

**Comment by SagarBudhathoki** [comment]
Hello @AnisH1427 
<img width="384" alt="image" src="https://github.com/AnisH1427/Traffic-Management-System/assets/125170137/6a57255c-904c-418c-8973-f51fde26f00c">
Regarding the unwanted data entry, I have implemented some fixes to ensure that only valid data is being entered into the database. The length of the mobile number is now being checked to ensure that it is equal to 10, and the email format is being validated to ensure that it is a valid email.
<img width="385" alt="image" src="https://github.com/AnisH1427/Traffic-Management-System/assets/125170137/43912e93-da4b-4aca-9ba9-043c6524c743">

This is a screenshot of valid data while creating police.
![image](https://github.com/AnisH1427/Traffic-Management-System/assets/125170137/de5eac22-ad4b-4ad3-b237-fd8c3180b523)
