### ISSUE TITLE
To ask confirmation when logging out

### ISSUE THREAD

**Issue by SauryaManandhar** [AnisH1427/Traffic-Management-System#12]
Dear developer, when I tried to log out, it logged out directly without asking the user/admin if they want to log out. I think the system should ask for confirmation(whether they want to log out or not) before logging out to the homepage.
Thank you.,
Saurya Manandhar

**Comment by SagarBudhathoki** [comment]
Hello @SauryaManandhar ,  I have fixed the issue with the logout functionality and added a confirmation dialogue to ensure that the user/admin wants to log out before redirecting to the homepage.
![image](https://github.com/AnisH1427/Traffic-Management-System/assets/125170137/5238ca3a-f2c5-4301-8a87-9e399d80c650)
