### ISSUE TITLE
Mis-functionality in Text

### ISSUE THREAD

**Issue by AnisH1427** [AnisH1427/Traffic-Management-System#13]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/102788439/229038435-f063501f-6884-409f-afe0-25c340c96960.png">
Hello developer, In above picture, you can see some text as Solutions in the homepage. But the problem is, it contains some of the functionality  during hoover; which is made of button.
Here is the issue 
<img width="293" alt="image" src="https://user-images.githubusercontent.com/102788439/229038756-423aacd5-0c35-4df8-98c8-a42339106779.png">
 So, I would like you to fix this issue.
Thank You.

**Comment by amritregmimagar** [comment]
I have noted it and I am working on it Anish. Thank you!

**Comment by AnisH1427** [comment]
I fixed it , closing the issue now.
