### ISSUE TITLE
Code Push on Github

### ISSUE THREAD

**Issue by amritregmimagar** [AnisH1427/Traffic-Management-System#14]
Dear Developer Sagar Budathoki, I would like to request you to push your code on Github. So, we can find the issue on our system together.

**Comment by AnisH1427** [comment]
> Dear Developer Sagar Budathoki, I would like to request you to push your code on Github. So, we can find the issue on our system together.

This is not an issue to be posted on github, and He has already push his code on repository. In issue section, you can only create an issue that arise inside the functionality of the Application.
