### ISSUE TITLE
Pending payment is not shown to User

### ISSUE THREAD

**Issue by AnisH1427** [AnisH1427/Traffic-Management-System#17]
Hello Contributor,

I encountered an issue while attempting to view the specific details of a pending bill from a user account, as the feature was not functioning properly. The intended purpose of this feature is to display all the relevant information related to a particular pending challan or bill.

Thank you for your assistance.
<img width="695" alt="BugReport1 - PaymentDetails not Showing" src="https://user-images.githubusercontent.com/102788439/234904124-dbbe41db-7a09-443d-b856-b325bfc05df0.png">

**Comment by SagarBudhathoki** [comment]
Hello @AnisH1427, Now, users will be able to view all the relevant information related to a particular pending challan or bill without any issues and feature is properly functioning.
![image](https://github.com/AnisH1427/Traffic-Management-System/assets/125170137/c6fbdb1d-a12d-4cee-b1f9-de0e6686343d)
