### ISSUE TITLE
Consistent Flow is not maintained

### ISSUE THREAD

**Issue by AnisH1427** [AnisH1427/Traffic-Management-System#3]
Hello contributor,
I’ve noticed that there is an issue with the consistent flow of the system when users login and register. Specifically, the flow is not maintained consistently throughout the process.

Also, It is very crucial to do client-site varification before sending Application data into database, so that appropriate data-type can be fetched into database without any problem
Could you please take a look at this issue and let me know what can be done to fix it?

Thank you!

**Comment by SagarBudhathoki** [comment]
done #8
