### ISSUE TITLE
Side bar not working

### ISSUE THREAD

**Issue by AnisH1427** [AnisH1427/Traffic-Management-System#5]
Hello contributor,
The sidebar in Admin Dashboard is also not functioning. So I kindly request our developer to fix this issue, Thank You.

**Comment by SagarBudhathoki** [comment]
done #8

**Comment by AnisH1427** [comment]
please donot confirm without fixing the issue.
<img width="960" alt="image" src="https://user-images.githubusercontent.com/102788439/229037681-20d68d4d-8d2f-45b3-8b32-5708bf9c8978.png">

**Comment by AnisH1427** [comment]
this featured is now removed .
