### ISSUE TITLE
`Save Police` button not working while adding Traffic Police

### ISSUE THREAD

**Issue by AnisH1427** [AnisH1427/Traffic-Management-System#9]
Hello developer,
<img width="949" alt="image" src="https://user-images.githubusercontent.com/102788439/229296994-cec942e0-9703-4505-a193-d7b6b7fc710a.png">

When admin wants to add new Police at a particular location, the submit button donot responds. There might be the possible problem while inserting into database, please check it. Thank You

**Comment by SagarBudhathoki** [comment]
done #8
